# Generated by Django 6.0.4 on 2026-04-20 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_lb', '0002_bucket_bucket_element'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='products/%Y/%m/%d/', verbose_name='Фото товара'),
        ),
    ]
