# Generated by Django 6.0.4 on 2026-06-08 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_lb', '0004_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AddField(
            model_name='profile',
            name='favorite_category',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Любимая категория'),
        ),
    ]
